spring.application.name=BigBazzarServer
spring.datasource.url=jdbc:mysql://localhost:3306/BigBazzar?createTableIfNotExists=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Mukulvats31124@gmail.com
spring.mail.password=jogsehpbmihawstr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secretKey=fdjfhdfgdhhfgdf6376646767267hgfsgfdhsgfaftetwrt7etr73t7ro